# Generated by Django 3.2.4 on 2021-06-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('parent_email', models.EmailField(max_length=245)),
                ('qrcode', models.ImageField(upload_to='')),
            ],
        ),
    ]
